import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { GuueyAgent, GuueyJsonV1 } from '@guuey/config';
import { mapHostedStateToOverlay, restorePlatformTemplates, type AppResponse, type PlatformTemplates } from './pull.js';

const APP: AppResponse = { id: 'app-1', displayName: 'Admin' };

const agent = (): GuueyAgent => ({
  mode: 'declarative',
  framework: 'claude-agent-sdk',
  model: 'claude-sonnet-5',
  mcpServers: {
    admin: { kind: 'external', url: 'https://admin-mcp.dev.sandbox.guuey.com/mcp', credential: 'oauth', mcpResourceUrl: 'https://admin-mcp.dev.sandbox.guuey.com/' },
    linear: { kind: 'external', url: 'https://mcp.linear.app/mcp', credential: 'oauth' },
    docs: { kind: 'hosted', server: 'docs-search' },
  },
  systemPrompt: 'You are the admin agent.',
});

describe('restorePlatformTemplates — the authored template goes back on the entry the door resolved (guuey#1272)', () => {
  it('rewrites url and mcpResourceUrl for the named external entries only; other entries and unknown names are untouched; null templates return the same agent', () => {
    const t: PlatformTemplates = { mcpServers: { admin: { url: 'https://${platform.adminMcpDomain}/mcp', mcpResourceUrl: 'https://${platform.adminMcpDomain}/' }, docs: { url: 'x' }, ghost: { url: 'y' } } };
    const out = restorePlatformTemplates(agent(), t);
    expect(out.mcpServers?.admin).toEqual({ kind: 'external', url: 'https://${platform.adminMcpDomain}/mcp', credential: 'oauth', mcpResourceUrl: 'https://${platform.adminMcpDomain}/' });
    expect(out.mcpServers?.linear).toEqual(agent().mcpServers?.linear);
    expect(out.mcpServers?.docs).toEqual(agent().mcpServers?.docs);
    expect(out.mcpServers?.ghost).toBeUndefined();
    const a = agent();
    expect(restorePlatformTemplates(a, null)).toBe(a);
  });
});

/**
 * The DOOR's own bytes: the fixture is generated by
 * `backend/amplify/functions/shared/fixtures/write-platform-templates-fixture.ts`
 * from the resolver, and pinned by the backend's test. Read by path here so
 * the CLI's restore is exercised on what the door actually returns; on the
 * withguuey/guuey-sdks mirror there is no backend/ and only this comparison
 * is skipped (the mirror law).
 */
const FIXTURE = fileURLToPath(new URL('../../../../../backend/amplify/functions/shared/fixtures/platform-templates-envelope.json', import.meta.url));
describe.skipIf(!existsSync(FIXTURE))('guuey pull round-trips the door\'s envelope back to the authored manifest', () => {
  it('the overlay carries the template, not the environment\'s host — and without the envelope field it carries the resolved url (today\'s behaviour, never below it)', () => {
    const fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as {
      manifest: GuueyJsonV1;
      envelope: { snapshot: GuueyJsonV1; platformTemplates: PlatformTemplates | null };
    };
    const { overlay } = mapHostedStateToOverlay(APP, fixture.envelope.snapshot, null, fixture.envelope.platformTemplates);
    const authored = fixture.manifest.agent.mcpServers?.admin;
    expect(authored !== undefined && authored !== false && authored.kind === 'external').toBe(true);
    if (authored !== undefined && authored !== false && authored.kind === 'external') {
      expect(overlay.agent.mcpServers?.admin).toMatchObject({ url: authored.url, mcpResourceUrl: authored.mcpResourceUrl });
    }
    expect(JSON.stringify(overlay.agent.mcpServers?.admin)).toContain('${platform.adminMcpDomain}');
    expect(overlay.agent.mcpServers?.linear).toEqual(fixture.envelope.snapshot.agent.mcpServers?.linear);
    const old = mapHostedStateToOverlay(APP, fixture.envelope.snapshot, null);
    expect(JSON.stringify(old.overlay.agent.mcpServers?.admin)).not.toContain('${platform.');
    expect(old.overlay.agent.mcpServers?.admin).toEqual(fixture.envelope.snapshot.agent.mcpServers?.admin);
  });
});
